# Generated by Django 6.0.4 on 2026-09-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=40)),
                ('primer_apellido_cliente', models.CharField(max_length=30)),
                ('segundo_apellido_cliente', models.CharField(blank=True, max_length=30)),
                ('correo_cliente', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('identificacion_empleado', models.IntegerField()),
                ('comentarios', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
