# Generated by Django 6.0.4 on 2026-09-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('identificacion_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=40)),
                ('primer_apellido_empleado', models.CharField(max_length=30)),
                ('segundo_apellido_empleado', models.CharField(blank=True, max_length=30)),
                ('correo_empleado', models.EmailField(max_length=100, unique=True)),
                ('telefono_empleado', models.CharField(max_length=20)),
                ('direccion_empleado', models.CharField(max_length=100)),
                ('password', models.CharField(db_column='hash_contrasena_empleado', max_length=200)),
                ('codigo_perfil_empleado', models.IntegerField()),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
