# Generated by Django 6.0.4 on 2026-09-03 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperio', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(blank=True, max_length=50, null=True)),
                ('operacion', models.CharField(blank=True, max_length=1, null=True)),
                ('momento', models.CharField(blank=True, max_length=1, null=True)),
                ('usuario_bd', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('codigo_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_venta', models.IntegerField()),
                ('codigo_producto', models.IntegerField()),
                ('cantidad_producto', models.IntegerField()),
                ('precio_unitario_producto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_ventas',
            },
        ),
        migrations.CreateModel(
            name='ErrorSistema',
            fields=[
                ('codigo_error', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_error', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'errores_sistema',
            },
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('codigo_estado_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_reparacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estados_servicio',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('codigo_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('codigo_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(max_length=50)),
                ('codigo_rol', models.IntegerField()),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='RelojCliente',
            fields=[
                ('codigo_reloj_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cliente', models.IntegerField()),
                ('codigo_marca', models.IntegerField()),
                ('modelo', models.CharField(max_length=15)),
                ('descripcion_reloj', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'relojes_cliente',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('codigo_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=50)),
                ('url_ruta', models.CharField(max_length=200)),
                ('nodo_ruta', models.CharField(max_length=1)),
                ('padre_ruta', models.IntegerField(blank=True, null=True)),
                ('orden_ruta', models.IntegerField()),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_tecnico', models.IntegerField()),
                ('codigo_tipo_servicio', models.IntegerField()),
                ('codigo_estado_servicio', models.IntegerField()),
                ('codigo_reloj_cliente', models.IntegerField()),
                ('codigo_detalle_venta', models.IntegerField(blank=True, null=True)),
                ('fecha_servicio', models.DateTimeField()),
                ('descripcion_falla', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('codigo_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_producto', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipo_productos',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('codigo_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_servicio', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipos_servicio',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo_venta', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion_cliente_venta', models.IntegerField()),
                ('identificacion_empleado_venta', models.IntegerField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField()),
                ('codigo_metodo_pago', models.IntegerField()),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro_cliente',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primer_apellido_cliente',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundo_apellido_cliente',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion_empleado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono_empleado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_perfil_permiso', models.IntegerField()),
                ('codigo_ruta_permiso', models.IntegerField()),
                ('consultar', models.CharField(max_length=1)),
                ('insertar', models.CharField(max_length=1)),
                ('modificar', models.CharField(max_length=1)),
                ('eliminar', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'permisos',
                'constraints': [models.UniqueConstraint(fields=('codigo_perfil_permiso', 'codigo_ruta_permiso'), name='uq_permisos_perfil_ruta')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=40)),
                ('codigo_marca', models.IntegerField()),
                ('codigo_tipo_producto', models.IntegerField()),
                ('modelo_producto', models.CharField(blank=True, max_length=15, null=True)),
                ('precio_venta_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garantia_producto', models.IntegerField()),
                ('descripcion_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_disponible_producto', models.IntegerField()),
                ('stock_minimo_producto', models.IntegerField()),
                ('controla_stock', models.CharField(max_length=1)),
                ('ultima_actualizacion_producto', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'constraints': [models.CheckConstraint(condition=models.Q(('controla_stock__in', ('S', 'N'))), name='ck_productos_control_stock')],
            },
        ),
    ]
